IRN ADM2 Metadata Validation
wmgeolab/gbRelease pull request #759
Opened 2020-12-19 16:56 UTC by kpupkiewicz

#442

## Why do we need this boundary?  

## Anything Unusual?

## Checklist:

- [x ] My submission is either a shapefile (with all the relevant files) or a geojson.
- [x ] I have included a file named "meta.txt", with all required metadata (see an example in https://bit.ly/2GtQ01i).
- [x ] I have included a file named "license.png" or "license.jpg", which includes a screenshot of the loaded website (or other source) with the licensure information.
- [x ] Everything is zipped up in a single file following the naming convention "ISO_ADMN.zip", and I am requesting it be added to the correct folder (i.e., gbOpen).

2020-12-21 04:39 UTC, nmspage requested changes
Please look into the holes in the polygons, and see if the holes accurately represent missing areas. It looks like a couple of cities (like Ishafan) were not included in this shapefile. If you need to make a new issue to find a different shapefile, let me know!

2021-01-28 17:40 UTC, slfuhrig commented
Please review again @nmspage

2021-02-01 23:24 UTC, nmspage approved these changes

2021-02-17 15:27 UTC, merged

2021-02-17 15:27 UTC, DanRunfola commented
Good to fix these holes.  Been plaguing us forever.

(Also, good stale bot!)